FunFoxTask/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FunFoxTask.FunFoxDbContext;
using FunFoxTask.Models;

namespace FunFoxTask.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CoursesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            return View(await _context.courses.ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.courses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CourseName,Grade,Timing,MaxSize")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                TempData["Notifications"] = Notification.SerializeNotifications(new List<Notification>() { new Notification("success", $"Course Added Successfully") });
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CourseName,Grade,Timing,MaxSize")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                    TempData["Notifications"] = Notification.SerializeNotifications(new List<Notification>() { new Notification("success", $"Course Edit Successfully") });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.courses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.courses.FindAsync(id);
            if (course != null)
            {
                _context.courses.Remove(course);
            }

            await _context.SaveChangesAsync();
            TempData["Notifications"] = Notification.SerializeNotifications(new List<Notification>() { new Notification("success", $"Course Deleted Successfully") });
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.courses.Any(e => e.Id == id);
        }
    }
}

FunFoxTask/Controllers/StudentsController.cs
using FunFoxTask.FunFoxDbContext;
using FunFoxTask.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FunFoxTask.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityAspNetUser> _userManager;

        public StudentsController(ApplicationDbContext context, UserManager<IdentityAspNetUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            var courses = _context.courses.ToList();
            var student = await _userManager.GetUsersInRoleAsync("Student");
            var students = student.Select(x => new Student
            {
                Id = x.Id,
                FirstName = x.FirstName,
                lastName = x.LastName,
                Username = x.UserName,
                Email = x.Email,
                CourseName = courses?.FirstOrDefault(y => y.Id == x.EnrolledCourse.GetValueOrDefault())?.CourseName
            }).ToList();
            return View(students);
        }

        public async Task<IActionResult> EnrolledCourse()
        {
            var user = await _userManager.GetUserAsync(User);
            ViewData["CourseName"] = _context.courses.FirstOrDefault(x => x.Id == user.EnrolledCourse)?.CourseName;
            return View(user);
        }

        public async Task<IActionResult> UnEnroll(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var course = await _context.courses.FirstOrDefaultAsync(x => x.Id == user.EnrolledCourse);
                if (course?.StudentsEnrolled != null)
                {
                    course.StudentsEnrolled -= 1;
                    _context.courses.Update(course);
                }
                user.EnrolledCourse = null;
                await _userManager.UpdateAsync(user);
                _context.SaveChangesAsync();
                TempData["Notifications"] = Notification.SerializeNotifications(new List<Notification>() { new Notification("success", $"UnEnroll Successfully") });
            }

            return RedirectToAction("Index");
        }
        
    }
}

FunFoxTask/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityAspNetUser> SignInManager
@{
    Layout = null;
    var notifications = Html.Raw("");
    if (TempData["Notifications"] != null)
    {
        notifications = Html.Raw(TempData["Notifications"]);
    }
    else
    {
        notifications = Html.Raw(Json.Serialize(new List<Notification>()));
    }

    var role = string.Empty;
    var isUserLoggedIn = SignInManager.IsSignedIn(User);
    if (isUserLoggedIn)
    {
        bool isAdmin = User.IsInRole("Admin");
        bool isPatient = User.IsInRole("Student");
        if (isAdmin)
        {
            role = "Admin";
        }
        else if (isPatient)
        {
            role = "Student";
        }
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FunFoxTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/FunFoxTask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FunFoxTask</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (role == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Students" asp-action="Index">Students</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Courses" asp-action="Index">Courses</a>
                            </li>
                        }
                        @if (role == "Student")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Students" asp-action="EnrolledCourse">Enrolled Course</a>
                            </li>
                        }
                        @if (!isUserLoggedIn)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="SignUp">SignUp</a>
                            </li>
                        }
                    </ul>
                    @if (isUserLoggedIn)
                    {
                        <a class="nav-link text-dark" asp-controller="Account" asp-action="SignOut">SignOut</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FunFoxTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


    <script>

        var notification = @notifications;
        $(document).ready(async function () {
            $.each(notification, function (index, value) {
                showNotification(value.Type, value.Description);
            });
        });

        function showNotification(type = 'info', message) {
            toastr.options = {
                closeButton: true,
                progressBar: false,
                timeOut: "5000",
                showMethod: "slideDown"
            };
            let title = '';
            if (type === 'info') {
                title = 'Information!'
            } else if (type === 'warning') {
                title = 'Warning!'
            } else if (type === 'success') {
                title = 'Success!'
            } else {
                title = 'Error!'
            }

            toastr[type](message, title);
        }
    </script>
</body>
</html>